import reflex as rx
from my_app_name.componets.link_button import link_button
from my_app_name.componets.title import title

def links() -> rx.Component:
    return rx.vstack(
        title("Documentacion"),
        link_button("html", 
                    "Tutorial html w3 School", 
                    "icons/html.svg",
                    "https://www.w3schools.com/html/"),
        link_button("css", 
                    "tutorial css w3 school", 
                    "icons/css.svg",
                    "https://www.w3schools.com/css/"),
        link_button("javascript", 
                    "Tutorial javascript developer mozilla",
                    "icons/javascript.svg",
                    "https://developer.mozilla.org/es/docs/Web/JavaScript"),
        link_button("php", 
                    "Documentacion oficial de php", 
                    "icons/php_dark.svg",
                    "https://www.php.net/"),
        link_button("python",
                    "tutorial de python", 
                    "icons/python.svg",
                    "https://docs.python.org/es/3.13/tutorial/index.html"),
        title("documentacion de framework"),
        link_button("React", 
                    "Documentacion oficial de react", 
                    "icons/react.svg",
                    "https://es.react.dev/"),
        link_button("Angular", 
                    "Documentacion oficial de Angular",
                    "icons/angular.svg",
                    "https://angular.dev/"),
        link_button("Vue.js",
                    "Documentacion oficial de vuejs",
                    "icons/vue.svg",
                    "https://vuejs.org/"),
        link_button("Reflex", "Documentacion oficial de reflex(python)",
                    "icons/favicon.ico",
                    "https://reflex.dev/"),
        title("caneles de youtube recomendados"),
        link_button("mouredev", 
                    "canal de programacion y desarrollo de software", 
                    "icons/youtube.svg",
                    "https://www.youtube.com/@mouredev"),
        link_button("Carlos Azaustre", 
                    "canal de programacion web y javascript", 
                    "icons/youtube.svg",
                    "https://www.youtube.com/@CarlosAzaustre"),
        link_button("ManzDev", "canal de developer web (css)",
                    "icons/manzdev.svg",
                    "https://www.youtube.com/@ManzDev"),
        link_button("Midudev","Todo sobre desarrollo web", 
                    "icons/midudev.svg",
                    "https://www.youtube.com/@midudev"),
        title("Tutoriales de ManzDev"),
        link_button("ManzDev","pagina pincipal ",
                    "icons/manzdev.svg", 
                    "https://manz.dev/"),
        link_button("html", "Aprende lenguaje HTML5 y etiquetas de html",
                    "icons/html.svg",
                    "https://lenguajehtml.com/html/"),
        link_button("css", "Lenguaje css (aspecto visual)", 
                    "icons/css.svg",
                    "https://lenguajecss.com/css/"),
        link_button("javascript", "Aprebnde el lenguaje de la web",
                    "icons/javascript.svg",
                    "https://lenguajejs.com/javascript/"),
        title("Rercursos"),
        link_button("ManzDev",
                    "Chuletas de distintos lenguajes",
                    "icons/manzdev.svg", 
                    "https://manz.dev/cheatsheets/"),
        link_button("readme", "La forma mas facil de crear un readme",
                    "icons/wrench.svg", 
                    "https://readme.so/es"),
        link_button("FreeSet", "Colecion de recurso para tu pagina web",
                    "icons/wrench.svg",  
                    "https://freesets.dev/"),
        link_button("chalk", 
                    "generador de background",
                    "icons/wrench.svg",  
                    "https://chalk.ist/"),
        width= "100%",
        spacing="3"
    )